data:
  dataRetention: forever
  dataRetentionValue: null
  fileUploadsAction: retain
  notifications:
    -
      attachFiles: true
      content: '[{"type":"paragraph","content":[{"type":"text","text":"A user submission has been made on the \""},{"type":"variableTag","attrs":{"label":"Form Name","value":"{formName}"}},{"type":"text","text":"\" form on "},{"type":"variableTag","attrs":{"label":"Site Name","value":"{siteName}"}},{"type":"text","text":" at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"text","text":"Their submission details are:"}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enabled: true
      name: 'Admin Notification'
      replyTo: '{field:emailAddress}'
      subject: 'A new submission was made on "{formName}"'
      to: '{systemEmail}'
    -
      attachFiles: true
      content: '[{"type":"paragraph","content":[{"type":"text","text":"Thanks again for contacting us. Our team will get back to you as soon as we can."}]},{"type":"paragraph","content":[{"type":"text","text":"As a reminder, you submitted the following details at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enabled: true
      name: 'User Notification'
      replyTo: null
      subject: 'Thanks for contacting us!'
      to: '{field:emailAddress}'
  pages:
    -
      label: 'Page 1'
      rows:
        -
          fields:
            -
              settings:
                enabled: true
                handle: yourName
                instructions: 'Please enter your full name.'
                instructionsPosition: verbb\formie\positions\AboveInput
                label: 'Your Name'
                labelPosition: verbb\formie\positions\Hidden
                placeholder: 'Your name'
                required: false
                rows:
                  -
                    fields:
                      -
                        settings:
                          enabled: false
                          handle: prefix
                          inputAttributes:
                            -
                              label: autocomplete
                              value: honorific-prefix
                          label: Prefix
                          options:
                            -
                              isDefault: true
                              isOptgroup: false
                              label: 'Select an option'
                              value: ''
                          required: false
                        type: verbb\formie\fields\subfields\NamePrefix
                      -
                        settings:
                          enabled: true
                          handle: firstName
                          inputAttributes:
                            -
                              label: autocomplete
                              value: given-name
                          label: 'First Name'
                          placeholder: 'e.g. Peter'
                          required: true
                        type: verbb\formie\fields\subfields\NameFirst
                      -
                        settings:
                          enabled: false
                          handle: middleName
                          inputAttributes:
                            -
                              label: autocomplete
                              value: additional-name
                          label: 'Middle Name'
                          required: false
                        type: verbb\formie\fields\subfields\NameMiddle
                      -
                        settings:
                          enabled: true
                          handle: lastName
                          inputAttributes:
                            -
                              label: autocomplete
                              value: family-name
                          label: 'Last Name'
                          placeholder: 'e.g. Sherman'
                          required: true
                        type: verbb\formie\fields\subfields\NameLast
                useMultipleFields: true
              type: verbb\formie\fields\Name
        -
          fields:
            -
              settings:
                enabled: true
                handle: emailAddress
                instructions: 'Please enter your email so we can get in touch.'
                label: 'Email Address'
                placeholder: 'e.g. psherman@wallaby.com'
                required: true
              type: verbb\formie\fields\Email
        -
          fields:
            -
              settings:
                enabled: true
                handle: message
                instructions: 'Please enter your comments.'
                label: Message
                placeholder: 'e.g. The reason for my enquiry is...'
                required: true
              type: verbb\formie\fields\MultiLineText
      settings:
        backButtonLabel: Back
        buttonsPosition: left
        saveButtonLabel: Save
        saveButtonStyle: link
        showBackButton: false
        showSaveButton: false
        submitButtonLabel: 'Contact us'
  settings:
    collectIp: false
    collectUser: false
    dataRetention: null
    dataRetentionValue: null
    defaultEmailTemplateId: null
    defaultInstructionsPosition: verbb\formie\positions\AboveInput
    defaultLabelPosition: verbb\formie\positions\AboveInput
    disableCaptchas: false
    displayCurrentPageTitle: false
    displayFormTitle: false
    displayPageProgress: false
    displayPageTabs: false
    errorMessage: '[{"type":"paragraph","content":[{"type":"text","text":"Couldnâ€™t save submission due to errors."}]}]'
    errorMessagePosition: top-form
    fileUploadsAction: null
    limitSubmissions: false
    limitSubmissionsMessage: null
    limitSubmissionsNumber: null
    limitSubmissionsType: null
    loadingIndicator: spinner
    loadingIndicatorText: null
    pageRedirectUrl: null
    progressPosition: end
    redirectUrl: null
    requireUser: false
    requireUserMessage: null
    requiredIndicator: asterisk
    scheduleForm: false
    scheduleFormEnd: null
    scheduleFormExpiredMessage: null
    scheduleFormPendingMessage: null
    scheduleFormStart: null
    scrollToTop: true
    submissionTitleFormat: '{timestamp}'
    submitAction: message
    submitActionFormHide: false
    submitActionMessage: '[{"type":"paragraph","content":[{"type":"text","text":"Thank you for contacting us! Our team will get in touch shortly to follow up on your message."}]}]'
    submitActionMessagePosition: top-form
    submitActionMessageTimeout: null
    submitActionTab: null
    submitActionUrl: null
    submitMethod: ajax
    validationOnFocus: true
    validationOnSubmit: true
  userDeletedAction: retain
defaultStatus: eaf2a29e-5cf9-4770-9177-0bb0c1c973aa # New
handle: contactForm
name: 'Contact Form'
submitActionEntry: null
template: null
