color: null
description: null
fieldLayouts:
  71660a2a-5e9c-456e-9584-e81e70baf6f2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T16:32:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0cf026d5-6d08-4e27-8a1f-ab30bca41c98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0102572d-d127-40b1-b9c0-704387cc932f
        userCondition: null
handle: pageBlocks
hasTitleField: true
icon: file
name: 'Page - Blocks'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
