columnSuffix: null
handle: lightswitchOn
instructions: null
name: 'Lightswitch - On'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
