columnSuffix: null
handle: lightswitchOff
instructions: null
name: 'Lightswitch - Off'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
