columnSuffix: null
handle: linkButtonNoLabel
instructions: null
name: 'Link / Button - No Label'
searchable: false
settings:
  advancedFields:
    - target
    - ariaLabel
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - '1'
            -
              - showUnpermittedEntries
              - '1'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
