columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
