columnSuffix: null
handle: video
instructions: null
name: Video
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 6176fd70-d37c-41e5-aca8-2f890c6d7866
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - d4f57e59-a9af-4745-827d-430501252655
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - videoUrl
                            2:
                              - label
                              - 'Video URL'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-10-24T09:22:22+00:00'
                            11:
                              - uid
                              - 0fe9b6d2-22ad-47c0-9064-2acb8c37e00a
                            14:
                              - fieldUid
                              - f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - videoThumbnail
                            2:
                              - label
                              - 'Video Thumbnail'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-10-24T09:22:22+00:00'
                            11:
                              - uid
                              - 7db705a8-027f-49d5-9fa2-b32a8bc15556
                            14:
                              - fieldUid
                              - 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
