dateModified: 1690286030
email:
  fromEmail: $SITE_EMAIL
  fromName: $SITE_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: $SMTP_HOSTNAME
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@assetBasePath/files'
    type: craft\fs\Local
    url: '@assetBaseUrl/files'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    type: craft\fs\Local
    url: '@assetBaseUrl/images'
meta:
  __names__:
    00cbe002-253f-4fca-b75f-ffc4cd309519: 'Site - Header Navigation' # Site - Header Navigation
    0cf15aa5-fa7d-405e-9a99-aa30b099a53c: Files # Files
    0f92aa22-16d7-46d4-876a-135fba91d971: 'Page - Block' # Page - Block
    1b7a3230-f24a-4ac2-a997-3289e43ddf25: 'Site - Cookie Consent' # Site - Cookie Consent
    2f26868b-418e-44a0-8e53-d367d9a163eb: 'Meta & Social Data' # Meta & Social Data
    4edb6c61-ee7b-4a62-ae07-d27f2127a80a: Block # Block
    06fb793a-57ef-483e-8415-675d2cfa2fd8: $SITE_NAME # $SITE_NAME
    07997af2-2846-44ff-a240-009561640c19: 'Links To' # Links To
    90552b17-3ba7-452a-9dfd-0b13004b4659: 'Page - Block Content' # Page - Block Content
    a4cade2e-b351-4d0b-8087-3328bc132811: Page # Page
    a37b06c6-894d-4dad-a768-46c1a840e80b: 'Craft 3' # Craft 3
    a6548a8e-edd2-4cbb-9200-db7de2726f75: Common # Common
    b59ae72a-8b0b-4bb9-83b9-a351b70b54a7: Site # Site
    d22d8c4e-5130-4bb2-afad-a7c08be98605: Images # Images
    d6471ab8-0d49-45bf-af5d-f0d2a860e267: 'Meta & Social Data' # Meta & Social Data
    f64c5171-437f-45f4-ac5b-1164673e94f9: Heading # Heading
    f733677f-fb59-4704-839a-4c90aa4b2d05: 'Public Schema' # Public Schema
    feb39789-b26f-45a4-99fb-d7e4cc376989: Padding # Padding
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 4.5.0
    settings:
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
      refreshMode: 3
  craft-dynamic-fields:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 1.0.0
  default-dashboard:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      excludeAdmin: ''
      logErrors: false
      logInfo: false
      override: '1'
      userDashboard: '1'
  freeform:
    edition: lite
    enabled: true
    licenseKey: null
    schemaVersion: 4.2.6
    settings:
      ajaxByDefault: false
      alertNotificationRecipients: null
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      exportLabels: false
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: false
      formSubmitExpiration: null
      formTemplateDirectory: _plugins/freeform
      formattingTemplate: flexbox.twig
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: true
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: Forms
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  imager-x:
    edition: lite
    enabled: true
    licenseKey: null
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 3.0.11
  seomatic:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: '604800'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: d22d8c4e-5130-4bb2-afad-a7c08be98605 # Images
  requireEmailVerification: true
