dateModified: 1605118717
email:
  fromEmail: $SITE_EMAIL
  fromName: $SITE_NAME
  replyToEmail: null
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz:
    edition: standard
    enabled: true
    schemaVersion: 3.6.6
  default-dashboard:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    schemaVersion: 3.1.0
  imager-x:
    edition: lite
    enabled: true
    schemaVersion: 3.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: '604800'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  schemaVersion: 3.5.13
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: d22d8c4e-5130-4bb2-afad-a7c08be98605
  requireEmailVerification: true
