dateModified: 1770115333
email:
  fromEmail: $CRAFT_SYSTEM_EMAIL
  fromName: $CRAFT_SITE_NAME
  replyToEmail: null
  template: _emails/system.twig
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  craftCloud:
    hasUrls: true
    name: 'Craft Cloud'
    settings:
      baseUrl: null
      expires: '1 years'
      localFsPath: '@webroot/uploads'
      localFsUrl: /uploads
      subpath: null
    type: craft\cloud\fs\AssetsFs
  local:
    hasUrls: true
    name: Local
    settings:
      path: $FILESYSTEM_LOCAL_BASE_PATH
    type: craft\fs\Local
    url: $FILESYSTEM_LOCAL_BASE_URL
  servd:
    hasUrls: true
    name: Servd
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      disableTransforms: false
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: /local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
meta:
  __names__:
    0b199c11-0b79-4e4b-b931-f9c85e23a667: 'Link / Button' # Link / Button
    1e8bf0d4-be2b-4c71-8c62-e6cbe9bc401d: Email # Email
    1fca19db-a5b4-4b81-addd-5d2fa40bb83d: 'Link / Button - No Label' # Link / Button - No Label
    2fa69ca1-0da9-4b6b-910a-16d9b40d3cad: File # File
    5cbe08b7-b4bd-4a6b-be41-de9647b5eb19: Images # Images
    5e0a0379-473d-48fa-b3f0-4230ddc449a6: 'Lightswitch - Off' # Lightswitch - Off
    6d792fe4-471d-48ed-bc45-5fe112ba7e46: Image # Image
    7b662bcd-ea91-4c91-86ce-c60348c664d1: Pages # Pages
    7bf65ac5-9169-4bf8-8825-65fadd566946: New # New
    7da91603-5ded-43ca-b8c9-692b445e049e: 'Rich Text - Longform' # Rich Text - Longform
    7f0dd947-99d8-4456-93f3-4ce4f6162a3f: 'Rich Text - Simple' # Rich Text - Simple
    8b610edc-f2dd-46b6-9597-96fcbb6d302a: Simple # Simple
    08c386f4-5a41-4c9f-8282-f6785af06bfc: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    42eea3c2-2f84-43d8-a495-647d4994a8d5: 'Text - Multiline' # Text - Multiline
    60dbe852-0ff6-4c8a-8bdc-6c303ebb6720: Longform # Longform
    69c481e3-79e8-4777-923b-472d305abcea: Full # Full
    453f9294-407d-405a-b73b-d5b63aec2eaa: SEO # SEO
    502c0610-e74d-4359-8524-5652307ada64: Padding # Padding
    824eedc9-d6b3-4bff-9b18-08c64927c6b0: Heading # Heading
    4580bc09-b5c8-40a2-bff5-95f715403f50: Video # Video
    13116ff7-bb9e-4f5b-989d-48a287e4b53c: 'Text - Code' # Text - Code
    41118d3a-a4e2-4b8e-8d11-b0a93f26deeb: 'Lightswitch - On' # Lightswitch - On
    13285537-5457-4f1f-ad8c-66fd187f8f09: 'Rich Text - Full' # Rich Text - Full
    b9ac68e1-d9f1-4007-843f-fde1e9f4921b: Files # Files
    bdf6317d-0df7-449f-a937-a1a274ffb106: 'Page - Blocks' # Page - Blocks
    c0203d6f-4eda-4753-879f-9c36db1c1a98: Date # Date
    c3b9838a-6581-409e-9730-3fecbd013c89: Phone # Phone
    cb6226c7-5901-41ed-ba28-a78b9504a3df: Images # Images
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    d5189384-3a6a-441f-9f4b-cb171f279337: Heading # Heading
    da9f3d8e-5ba9-4eb9-a423-6ea09ddaed21: Form # Form
    f3e544b8-88bf-4761-8df2-d767fa1502b7: Text # Text
    fb0420bb-0fbf-46d2-afd2-f7992c60c886: 'Contact Form' # Contact Form
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 5.12.0
    settings:
      maxUriLength: 2048
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 3.4.12
  imager-x:
    edition: lite
    enabled: true
    licenseKey: null
    schemaVersion: 4.0.0
  imager-x-craft-cloud-transformer:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: null
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: $SERVD_ASSET_ENVIRONMENT
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: never
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: '1'
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: '1'
      useLocalVolumes: false
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
