#ddev-generated
services:
  cypress:
    image: cypress/included:13.17.0
    container_name: ddev-${DDEV_SITENAME}-cypress
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    user: "${DDEV_UID}:${DDEV_GID}"
    networks: [default, ddev_default]

    tty: true

    environment:
      - CYPRESS_baseUrl=${DDEV_PRIMARY_URL}
      - DISPLAY
      - HOME=/root

    volumes:
      # Mount the project root to Cypress's project point
      - "${DDEV_APPROOT}:/e2e"
      # Mount DDEV to allow commands
      - ".:/mnt/ddev_config"
      # Allow X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix

    entrypoint: /bin/bash
    working_dir: /e2e
